claim_index:
    path:     /
    defaults: { _controller: "HeavenTNBundle:Claim:index" }
    methods:  GET

claim_show:
    path:     /{idclaim}/show
    defaults: { _controller: "HeavenTNBundle:Claim:show" }
    methods:  GET

claim_new:
    path:     /new
    defaults: { _controller: "HeavenTNBundle:Claim:new" }
    methods:  [GET, POST]

claim_edit:
    path:     /{idclaim}/edit
    defaults: { _controller: "HeavenTNBundle:Claim:edit" }
    methods:  [GET, POST]


claim_approve:
    path:     /{idclaim}/approve
    defaults: { _controller: "HeavenTNBundle:Claim:approve" }
    methods:  [GET, POST]

claim_ignore:
    path:     /{idclaim}/ignore
    defaults: { _controller: "HeavenTNBundle:Claim:ignore" }
    methods:  [GET, POST]


claim_delete:
    path:     /{idclaim}/delete
    defaults: { _controller: "HeavenTNBundle:Claim:delete" }
    methods:  DELETE


claim_sort:
    path:     /sort/{sort}
    defaults: { _controller: "HeavenTNBundle:Claim:sort" }
    methods:  GET