<?php

namespace HeavenTNBundle\Repository;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUser($id)
    {
        $query=$this->createQueryBuilder('c')
            ->select('c')
            ->where('IDENTITY(c.user)= :user_id')
            ->setParameter('user_id',$id)
        ->distinct('IDENTITY(c.product)')
        ->getQuery();


        return $query->getResult();


    }

    public function findByProduct($idp,$idu)
    {
        $query=$this->getEntityManager()
            ->createQuery(" SELECT c FROM HeavenTNBundle:Cart c where IDENTITY(c.product)= :product_id
            AND IDENTITY(c.user)= :user_id ")
            ->setParameter('product_id',$idp)
            ->setParameter('user_id',$idu);


        return $query->getResult();


    }








    public function deleteAllFromCart($user)
    {
        $query=$this->getEntityManager()
            ->createQuery('Delete   HeavenTNBundle:Cart p where IDENTITY(p.user)= :user
              ')->setParameter('user',$user);
        return $query->getResult();
    }





}
