<?php

namespace HeavenTNBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function  findByClient($id)
    {
        $query=$this->getEntityManager()->createQuery("SELECT m FROM HeavenTNBundle:Commande m WHERE m.client='$id' ");
        return $query->getResult();
    }
}
