<?php

namespace HeavenTNBundle\Repository;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUser($id)
    {
        $query=$this->createQueryBuilder('c')
            ->select('c')
            ->where('IDENTITY(c.user)= :user_id')
            ->setParameter('user_id',$id)
            ->distinct('IDENTITY(c.review)')
            ->getQuery();


        return $query->getResult();


    }
}
